name: .NET

on:
  push:
    branches:
     - master
     - develop
     - projectrename
     
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build IoT Edge Solution
      run: docker build  --rm -f "/modules/AntminerResetModule/Dockerfile.arm32v7.debug" -t mharris867/antminerresetmodule:0.0.3-arm32v7.debug "/modules/AntminerResetModule"

