name: Build IoT Edge Module

on:
  push:
    branches:
     - master
     - develop
     - projectrename

  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Create Credential File
      env:
        PWORD: ${{ secrets.PWORD }}
      shell: pwsh
      run: |
        $User = "root"
        $PWord = ConvertTo-SecureString -String "${env:PWORD}" -AsPlainText -Force
        $creds = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
        $creds | Export-CliXml -Path "./modules/AntminerResetModule/PSCreds_.xml"
    - name: Set Version number
      shell: pwsh
      run: |
        $MajorVersion = 1
        $MinorVersion = 0
        $SpanFromY2K = New-TimeSpan -Start (Get-Date "1/1/2000 12:00 AM") -End (Get-Date)
        $SubMajor = $SpanFromY2K.Days
        $CurrDay = New-TimeSpan -Start (Get-Date -Hour 0 -Minute 00 -Second 00) -End (Get-Date)
        [int]$SubMinor = $CurrDay.TotalSeconds / 2
        if ($env:GITHUB_REF_NAME -Like '*master*') {Add-Content -Path $env:GITHUB_ENV -Value "VERSION_INFO=$MajorVersion.$MinorVersion.$SubMajor.$SubMinor"}
        else {
        $prereleasesuffix = $env:GITHUB_REF_NAME.Substring($env:GITHUB_REF_NAME.LastIndexOf("/") + 1).Replace("_", "-").Replace(".", "-")
        $prereleasesuffix = $prereleasesuffix.Substring(0, [System.Math]::Min(19, $prereleasesuffix.Length))
        Add-Content -Path $env:GITHUB_ENV -Value "VERSION_INFO=$MajorVersion.$MinorVersion.$SubMajor.$SubMinor-$prereleasesuffix"
        }
        $module = (get-content ./modules/AntminerResetModule/module.json | ConvertFrom-Json)
        $module.image.tag.version = "$MajorVersion.$MinorVersion.$SubMajor.$SubMinor"
        $module | ConvertTo-Json -Depth 100 | set-content ./modules/AntminerResetModule/module.json
        Write-Host "Version Set To: $MajorVersion.$MinorVersion.$SubMajor.$SubMinor"
    - name: Build IoT Edge Solution
      run: docker build  --rm -f "./modules/AntminerResetModule/Dockerfile.arm32v7.debug" -t mharris867/antminerresetmodule:${{ env.VERSION_INFO }}-arm32v7.debug "./modules/AntminerResetModule"

