name: Build IoT Edge Module

on:
  push:
    branches:
     - master
     - develop
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'
    - name: Create Credential File
      env:
        PWORD: ${{ secrets.PWORD }}
      shell: pwsh
      run: |
        $User = "root"
        $PWord = ConvertTo-SecureString -String "${env:PWORD}" -AsPlainText -Force
        $creds = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
        $creds | Export-CliXml -Path "./modules/AntminerResetModule/PSCreds_.xml"
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        updateAssemblyInfo: true
    - name: List Variables
      shell: pwsh
      run: |
        Write-Host "Listing Available Environment Variables"
        get-childitem "env:"
        Write-Host "------------- End of Variable List -------------------"
    - name: Set Version number
      shell: pwsh
      run: |
        $MajorVersion = 1
        $MinorVersion = 0
        $SpanFromY2K = New-TimeSpan -Start (Get-Date "1/1/2000 12:00 AM") -End (Get-Date)
        $SubMajor = $SpanFromY2K.Days
        $CurrDay = New-TimeSpan -Start (Get-Date -Hour 0 -Minute 00 -Second 00) -End (Get-Date)
        [int]$SubMinor = $CurrDay.TotalSeconds / 2
        if ($env:GITHUB_REF_NAME -Like '*master*') {Add-Content -Path $env:GITHUB_ENV -Value "VERSION_INFO=$MajorVersion.$MinorVersion.$SubMajor.$SubMinor"}
        else {
        $prereleasesuffix = $env:GITHUB_REF_NAME.Substring($env:GITHUB_REF_NAME.LastIndexOf("/") + 1).Replace("_", "-").Replace(".", "-")
        $prereleasesuffix = $prereleasesuffix.Substring(0, [System.Math]::Min(19, $prereleasesuffix.Length))
        Add-Content -Path $env:GITHUB_ENV -Value "VERSION_INFO=$MajorVersion.$MinorVersion.$SubMajor.$SubMinor-$prereleasesuffix"
        }
        $module = (get-content ./modules/AntminerResetModule/module.json | ConvertFrom-Json)
        $module.image.tag.version = "$MajorVersion.$MinorVersion.$SubMajor.$SubMinor"
        $module | ConvertTo-Json -Depth 100 | set-content ./modules/AntminerResetModule/module.json
        Write-Host "Version Set To: $MajorVersion.$MinorVersion.$SubMajor.$SubMinor"
    - name: Build IoT Edge Solution PR
      if: ${{ github.event_name == 'pull_request' }}
      run: docker build  --rm -f "./modules/AntminerResetModule/Dockerfile.arm32v7.debug" -t localhost:5000/antminerresetmodule:${{ env.VERSION_INFO }}-arm32v7.debug "./modules/AntminerResetModule" && docker push localhost:5000/antminerresetmodule:${{ env.VERSION_INFO }}-arm32v7.debug
    - name: Build IoT Edge Solution
      if: ${{ contains(github.ref, 'master') || contains(github.ref, 'develop') }}
      run: docker build  --rm -f "./modules/AntminerResetModule/Dockerfile.arm32v7.debug" -t mharris867/antminerresetmodule:${{ env.VERSION_INFO }}-arm32v7.debug "./modules/AntminerResetModule" && docker push mharris867/antminerresetmodule:${{ env.VERSION_INFO }}-arm32v7.debug
    - name: Generate IoT Edge Deployment Manifiest
      run: iotedgedev genconfig -f ./deployment.debug.template.json -P arm32v7 --fail-on-validation-error
    - name: Install GitReleaseManager
      uses: gittools/actions/gitreleasemanager/setup@v0.9.13
      with:
        versionSpec: '0.10.x'
    - name: Publish release with GitReleaseManager
      uses: gittools/actions/gitreleasemanager/publish@v0.9.13
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tagName: '0.0.1'
        owner: 'mharris867'
        repository: 'AntminerReset'
